#!/bin/sh
boinccmd --get_tasks | sed -n '1,2!p' | awk 'NR%21==2 || NR%21==18 || NR%21==0' | sed -e 's/[^:]*: //' | awk '
{
    if (NR%3) {
        x = (NR-NR%3)/3+1
    } else {
        x = NR/3
    }
    f[x] = f[x] "\t" $i
    if (x > n) n = x
}
END {
    for (i = 1; i <= n; i++) print f[i]
}
' | awk '
{
    if ($3 > 50000 && $2 < 0.05) {
        print "boinccmd --task http://www.worldcommunitygrid.org/ " $1 " abort"
    }
}
' | bash
